stages:          
  - build
  - test
  - deploy

build-job:       
  stage: build
  parallel: 3
  script:
    - env
    - echo "Compiling the code..." # damn
    - echo "Compile complete."

unit-test-job:   
  stage: test   
  script:
    - echo "Running unit tests... This will take about 60 seconds......"
    - sleep 10
    - echo "Code coverage is 90%"

lint-test-job:   
  stage: test   
  script:
    - echo "Linting code... This will take about 10 seconds."
    - sleep 10
    - echo "No lint issues found."

deploy-dev:     
  stage: deploy
  environment: dev
  needs:
    - unit-test-job
    - lint-test-job
  when: manual
  script:
    - echo "Deploying application damn...test....test................"
    - echo "Application successfully deployed."

deploy-staging:     
  stage: deploy
  environment: staging
  needs:
    - unit-test-job
    - lint-test-job
  when: manual
  script:
    - echo "Deploying application..."
    - echo "Application successfully deployed."

deploy-production:     
  stage: deploy
  environment: production
  needs:
    - unit-test-job
    - lint-test-job
  script:
    - echo "Deploying application..."
    - echo "Application successfully deployed."
